# This file was generated by GoReleaser. DO NOT EDIT.
class Func < Formula
  desc ""
  homepage ""
  version "0.0.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/spring-media/func/releases/download/v0.0.9/func_0.0.9_darwin_amd64.tar.gz"
    sha256 "aa57131b396690ae3cb6b86a6f903561ddf3698d829697b78c8cd98bdab680ab"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/spring-media/func/releases/download/v0.0.9/func_0.0.9_linux_amd64.tar.gz"
      sha256 "e04375a7a10fc4502798595b10334663e20041f26dd4b55401a099ac8166ea03"
    end
  end

  def install
    bin.install "func"
  end

  test do
    system "#{bin}/func", "version"
  end
end
