# This file was generated by GoReleaser. DO NOT EDIT.
class Func < Formula
  desc ""
  homepage ""
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/spring-media/func/releases/download/v0.0.2/func_0.0.2_darwin_amd64.tar.gz"
    sha256 "d8a364fd3c7e1c834b013e1ad5b7bc87e695cc80eba7d4072298bec3481037a3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/spring-media/func/releases/download/v0.0.2/func_0.0.2_linux_amd64.tar.gz"
      sha256 "68594213e4dc6804aaef26192fcd04045b7fb1ca5fc19c48c17d10c1b9b7a902"
    end
  end

  def install
    bin.install "func"
  end

  test do
    system "#{bin}/func", "version"
  end
end
