# This file was generated by GoReleaser. DO NOT EDIT.
class Func < Formula
  desc ""
  homepage ""
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/spring-media/func/releases/download/v0.0.4/func_0.0.4_darwin_amd64.tar.gz"
    sha256 "dddd6b5d5c7e01812a6dd2919e90ec9862a6e9d30276b9de0d70622d66f38dcb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/spring-media/func/releases/download/v0.0.4/func_0.0.4_linux_amd64.tar.gz"
      sha256 "70091a1aaac696b12a0353639d7d1839168b7e61739545a4956713e934d5531b"
    end
  end

  def install
    bin.install "func"
  end

  test do
    system "#{bin}/func", "version"
  end
end
